# Número de Aluno: 123762  || Nome: Rodrigo Emanuel dos Santos Couceiro
# Code Smell: Duplicate Code (Fowler)
# Inspection ID: DuplicateExpressions


name: "Code Smell - Duplicate Code"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  detect-duplicate-code:
    runs-on: ubuntu-latest
    name: "Detect Duplicate Code (Fowler)"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2025.3
        with:
          pr-mode: false
          args: --config,qodana.yaml,--save-report

        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_2026785207 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: duplicate-code-report
          path: ${{ runner.temp }}/qodana/results/
          retention-days: 14
