# Número de Aluno: 123762  || Nome: Rodrigo Emnanuel dos Santos Couceiro
name: Qodana Code Analysis - Duplicate Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2025.3
        with:
          linter: jetbrains/qodana-jvm:2025.3
          cache-default-branch-only: true

      - name: Upload Qodana results
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: qodana-report
